version: "3.1"
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    container_name: transaction-app
    links:
      - db
    networks:
      - pp-network
    ports:
      - '8000:8000'

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: transaction-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./docker-configuration:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
    networks:
      - pp-network
    ports:
      - "3306:3306"


networks:
  pp-network:
    driver: bridge
